"""initial schema

Revision ID: b8c733334785
Revises: 
Create Date: 2026-04-05 12:48:44.392581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b8c733334785'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('corpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tradition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('era', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tradition_id'], ['tradition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('corpus_level',
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.PrimaryKeyConstraint('corpus_id', 'height')
    )
    op.create_table('unit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unit_corpus_height', 'unit', ['corpus_id', 'height'], unique=False)
    op.create_index('ix_unit_parent', 'unit', ['parent_id'], unique=False)
    op.create_table('embedding',
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('unit_id', 'model_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embedding')
    op.drop_index('ix_unit_parent', table_name='unit')
    op.drop_index('ix_unit_corpus_height', table_name='unit')
    op.drop_table('unit')
    op.drop_table('corpus_level')
    op.drop_table('corpus')
    op.drop_table('tradition')
    # ### end Alembic commands ###
